-- 05-recurring-tasks.sql
-- Run ONCE in the Supabase SQL Editor. Backs the "Daily" view.
--
-- Recurring daily tasks ("draw", "exercise") are a separate stream from
-- dated tasks: they reset every day and never appear on the calendar.
-- Two tables:
--   recurring_task        — the definitions (per user, orderable, archivable)
--   recurring_completion  — one row per task per day it was checked off.
--     "Done today" = a row exists for today; the daily reset is derived —
--     at midnight there's simply no row for the new day yet. Unchecking
--     deletes the row. No cron, no triggers.
-- The web app never touches these tables, so there is zero legacy impact.

create table if not exists public.recurring_task (
  id bigint generated by default as identity primary key,
  user_uuid uuid not null references auth.users (id) on delete cascade,
  title varchar(100) not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  -- Archived instead of deleted so completion history survives.
  archived_at timestamptz
);

create table if not exists public.recurring_completion (
  recurring_task_id bigint not null references public.recurring_task (id) on delete cascade,
  user_uuid uuid not null references auth.users (id) on delete cascade,
  done_on date not null,
  primary key (recurring_task_id, done_on)
);

create index if not exists recurring_task_user_idx on public.recurring_task (user_uuid);
create index if not exists recurring_completion_user_day_idx
  on public.recurring_completion (user_uuid, done_on);

-- RLS: same wall as `task` — you are your uuid, or you get nothing.
alter table public.recurring_task enable row level security;
alter table public.recurring_completion enable row level security;

grant select, insert, update, delete on public.recurring_task to authenticated;
grant select, insert, update, delete on public.recurring_completion to authenticated;
grant usage, select on sequence public.recurring_task_id_seq to authenticated;

create policy "read own recurring" on public.recurring_task
  for select to authenticated using (auth.uid() = user_uuid);
create policy "insert own recurring" on public.recurring_task
  for insert to authenticated with check (auth.uid() = user_uuid);
create policy "update own recurring" on public.recurring_task
  for update to authenticated using (auth.uid() = user_uuid) with check (auth.uid() = user_uuid);
create policy "delete own recurring" on public.recurring_task
  for delete to authenticated using (auth.uid() = user_uuid);

create policy "read own completions" on public.recurring_completion
  for select to authenticated using (auth.uid() = user_uuid);
create policy "insert own completions" on public.recurring_completion
  for insert to authenticated with check (auth.uid() = user_uuid);
create policy "update own completions" on public.recurring_completion
  for update to authenticated using (auth.uid() = user_uuid) with check (auth.uid() = user_uuid);
create policy "delete own completions" on public.recurring_completion
  for delete to authenticated using (auth.uid() = user_uuid);

-- Sanity check (read-only) — expect 8 rows:
--   select tablename, policyname from pg_policies
--   where tablename in ('recurring_task', 'recurring_completion');
