-- 10-security-hardening.sql
-- Run ONCE in the Supabase SQL Editor, after 09. Safe to re-run (every
-- statement is guarded or idempotent by nature).
--
-- Findings from the 2026-07-15 security/sync audit:
--   A. event.id is GENERATED ALWAYS — PowerSync uploads send explicit ids,
--      Postgres rejects them (428C9), the connector drops the ops, and the
--      next sync checkpoint erases the locally imported events. Silent, total
--      loss of every CSV import in sync mode. BY DEFAULT accepts explicit ids
--      (recurring_task already does this; task uses a plain nextval default).
--   B. The email-matching link (02's trigger + 03's backfill) trusted
--      UNCONFIRMED emails: with "Confirm email" off, anyone could sign up as
--      a legacy web user's address and inherit their tasks. Both paths now
--      require email_confirmed_at.
--      ⚠ IMPORTANT CAVEAT: this gate only means something while the
--      "Confirm email" dashboard toggle is ON. With it OFF, Supabase
--      auto-confirms signups (email_confirmed_at gets set immediately), so
--      the check passes for an attacker too. "Confirm email = ON" is
--      therefore a SECURITY INVARIANT for as long as email-match linking
--      exists — never turn it off again.
--   C. RLS on task never constrained the legacy user_id column — any
--      authenticated user could INSERT/UPDATE rows with an arbitrary user_id
--      and plant content in a web user's list. Column-level grants now
--      exclude user_id (only the trigger, running as owner, fills it).
--   D. recurring_completion INSERT only checked user_uuid = auth.uid(), not
--      that the referenced recurring_task is YOURS — an attacker could insert
--      a completion row against a victim's (guessable, sequential) task id
--      and permanently block their daily check-off via the unique constraint.
--   E. avatars bucket had no size or MIME limits: any authenticated user got
--      unlimited public file hosting under the project domain.

-- ========================================================================
-- A. event.id accepts client-minted ids (sync mode)
-- ========================================================================
alter table public.event alter column id set generated by default;

-- ========================================================================
-- B. Email links require CONFIRMED emails
-- ========================================================================
create or replace function public.task_fill_user_keys()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.user_uuid is null and new.user_id is not null then
    -- Insert came from the Java web app: attach the Supabase identity too,
    -- if this user has signed up natively AND confirmed the email.
    select u.id into new.user_uuid
    from public.app_users a
    join auth.users u on lower(u.email) = lower(a.email)
    where a.id = new.user_id
      and u.email_confirmed_at is not null;
  elsif new.user_id is null and new.user_uuid is not null then
    -- Insert came from the native app: attach the legacy identity too, but
    -- only once the Supabase account's email is confirmed (otherwise an
    -- unconfirmed signup could bridge into a web user's account).
    select a.id into new.user_id
    from auth.users u
    join public.app_users a on lower(a.email) = lower(u.email)
    where u.id = new.user_uuid
      and u.email_confirmed_at is not null;
  end if;
  return new;
end;
$$;
-- (03-link-existing-tasks.sql got the same confirmed-email condition — use
-- the updated copy in this folder if you re-run it.)

-- ========================================================================
-- C. authenticated may no longer write the legacy user_id column
-- ========================================================================
-- Row policies still gate by user_uuid; this closes the column Hibernate owns.
-- The trigger (SECURITY DEFINER, runs as table owner) still fills user_id.
revoke insert, update on public.task from authenticated;
grant insert (task_id, title, description, due_date, creation_date,
              is_completed, subject, subject_color, category, category_color,
              priority, user_uuid, deleted_at)
  on public.task to authenticated;
grant update (task_id, title, description, due_date, creation_date,
              is_completed, subject, subject_color, category, category_color,
              priority, user_uuid, deleted_at)
  on public.task to authenticated;

-- ========================================================================
-- D. completions must reference YOUR recurring task
-- ========================================================================
drop policy if exists "insert own completions" on public.recurring_completion;
create policy "insert own completions" on public.recurring_completion
  for insert to authenticated
  with check (
    auth.uid() = user_uuid
    and exists (
      select 1 from public.recurring_task rt
      where rt.id = recurring_task_id
        and rt.user_uuid = auth.uid()
    )
  );

-- ========================================================================
-- E. avatars bucket: images only, 1 MB cap
-- ========================================================================
update storage.buckets
set file_size_limit = 1048576,
    allowed_mime_types = array['image/jpeg', 'image/png', 'image/webp']
where id = 'avatars';

-- ========================================================================
-- F. events: end may not precede start (belt for the client-side check)
-- ========================================================================
do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'event_end_after_start'
  ) then
    alter table public.event
      add constraint event_end_after_start check (end_at is null or end_at >= start_at);
  end if;
end $$;

-- ========================================================================
-- Sanity checks (read-only):
--   select attname from pg_attribute a
--     join pg_class c on c.oid = a.attrelid
--    where c.relname = 'event' and attname = 'id';  -- exists
--   select identity_generation from information_schema.columns
--    where table_name = 'event' and column_name = 'id';   -- BY DEFAULT
--   select policyname from pg_policies
--    where tablename = 'recurring_completion' and cmd = 'INSERT';
-- ========================================================================
